(ns cpe.calculations.raw)
(def schema {
 :FC230131.PV :Recycle-H2-To-Pass-A
 :FI23A130.PV :Recycle-H2-To-Pass-B
 :FI230207.PV :Make-Up-Gas-From-Unicrack-H2
 :PI231220.PV :RX-A-1-Inlet-Pressure
 :TI230137.PV :RX-A-1-Feed-From-Heater-A
 :TI231201.PV :RX-A-1-Top-Bed-Up-A
 :TI231202.PV :RX-A-1-Top-Bed-Up-B
 :TI231203.PV :RX-A-1-Top-Bed-Up-C
 :TI231204.PV :RX-A-1-Top-Bed-Low-D
 :TI231205.PV :RX-A-1-Top-Bed-Low-E
 :TI231206.PV :RX-A-1-Top-Bed-Low-F
 :FC231200.PV :H2-Quench-To-MID-RX-A-1
 :TI231207.PV :RX-A-1-Bot-Bed-Up-G
 :TC231208.PV :RX-A-1-Bot-Bed-Up-H
 :TI231209.PV :RX-A-1-Bot-Bed-Up-I
 :TI231210.PV :RX-A-1-Bot-Bed-Mid-J
 :TI231211.PV :RX-A-1-Bot-Bed-Mid-K
 :TI231212.PV :RX-A-1-Bot-Bed-Mid-L
 :TI231213.PV :RX-A-1-Bot-Bed-Low-M
 :TI231214.PV :RX-A-1-Bot-Bed-Low-N
 :TI231215.PV :RX-A-1-Bot-Bed-Low-O
 :DI231225.PV :RX-A-1-Overall-Delta-P
 :TI231219.PV :RX-B-1-Outlet-Temp
 :FC231226.PV :H2-Quench-RX-A-2-Inlet
 :TC231227.PV :RX-A-2-Inlet-Top
 :TI231228.PV :A-2-Reactor-Bed-A
 :TI231229.PV :A-2-Reactor-Bed-B
 :TI231230.PV :A-2-Reactor-Bed-C
 :DI231233.PV :Reactor-A-2-Diff-Press
 :PI231231.PV :Reactor-A-Inlet
 :TI230144.PV :Reactor-A-Outlet
 :PI231320.PV :RX-B-1-Inlet-Pressure
 :TI230152.PV :RX-Feed-From-Heater-B
 :TI231301.PV :RX-B-1-Top-Bed-Up-A
 :TI231302.PV :RX-B-1-Top-Bed-Up-B
 :TI231303.PV :RX-B-1-Top-Bed-Up-C
 :TI231304.PV :RX-B-1-Top-Bed-Low-D
 :TI231305.PV :RX-B-1-Top-Bed-Low-E
 :TI231306.PV :RX-B-1-Top-Bed-Low-F
 :FC231300.PV :H2-Quench-To-MID-RX-B-1
 :TI231307.PV :RX-B-1-Bot-Bed-Up-G
 :TC231308.PV :RX-B-1-Bot-Bed-Up-H
 :TI231309.PV :RX-B-1-Bot-Bed-Up-I
 :TI231310.PV :RX-B-1-Bot-Bed-Mid-J
 :TI231311.PV :RX-B-1-Bot-Bed-Mid-K
 :TI231312.PV :RX-B-1-Bot-Bed-Mid-L
 :TI231313.PV :RX-B-1-Bot-Bed-Low-M
 :TI231314.PV :RX-B-1-Bot-Bed-Low-N
 :TI231315.PV :RX-B-1-Bot-Bed-Low-O
 :DI231325.PV :RX-B-1-Overall-Delta-P
 :FC231326.PV :H2-Quench-RX-B-2-Inlet
 :TC231327.PV :RX-B-2-Inlet-Temp
 :TI231328.PV :B-2-Reactor-Bed-A
 :TI231329.PV :B-2-Reactor-Bed-B
 :TI231330.PV :B-2-Reactor-Bed-C
 :DI231333.PV :Reactor-B-2-Diff-Press
 :TI230157.PV :Reactor-B-2-Outlet
 :02PCRGH.IM :Recycle-Gas-H2
 :02PCRGH2S.IM :Recycle-Gas-H2S
 :02PCMUH.IM :Makeup-H2
 :02APIGR.IM :Gravity
 :02DISIBP.IM :Initial-Boiling-Point-Test-Method-D2887
 :02DIS5P.IM  :Percent-5-Recovered-Test-Method-ASTM-D2887
 :02DIS10P.IM :Percent-10-Recovered-Test-Method-ASTM-D2887
 :02DIS20P.IM :Percent-20-Recovered-Test-Method-ASTM-D2887
 :02DIS30P.IM :Percent-30-Recovered-Test-Method-ASTM-D2887
 :02DIS40P.IM :Percent-40-Recovered-Test-Method-ASTM-D2887
 :02DIS50P.IM :Percent-50-Recovered-Test-Method-ASTM-D2887
 :02DIS60P.IM :Percent-60-Recovered-Test-Method-ASTM-D2887
 :02DIS70P.IM :Percent-70-Recovered-Test-Method-ASTM-D2887
 :02DIS80P.IM :Percent-80-Recovered-Test-Method-ASTM-D2887
 :02DIS90P.IM :Percent-90-Recovered-Test-Method-ASTM-D2887
 :02DIS95P.IM :Percent-95-Recovered-Test-Method-ASTM-D2887
 :02DISFBP.IM :Final-Boiling-Point-Test-Method-D2887
 :02WPSXRA.IM :SULFUR-WT%-X-RA-Result
 :02WPSUL.IM :Sulfur
 :fc230322.pv :Net-Diesel-To-Storage
 :fc230323.pv :Net-Kerosene-To-Storage
 :02PPCN2.IM :Charge-N2
 :02PPPN2.IM :Product-N2
 :02PPKS.IM :Kero-Sulfur
 :02FCFR.IM :Combined-Feed-Rate
 :02FCDBFR.IM :Coker-Debutanizer-Bottoms-Feed-Rate
 :02FNCDFR.IM :Net-Coker-Diesel
 :02LAPAGN :Prod-API-Gravity-Naphtha
 :02FPR.IM :Purge-Rate
 :02LAUPG :ULSD-Prod-Gravity
 :02LASIF :Sifeed
 :02LAASF :Asfeed})


(def calculated-sensor {:Normalized-HDS-WABT-Column-MI 334
                        :Normalized-HDB-WABT-Column-MS 335
                        :Feed-Sulfur-Column-CZ 336
                        :Product-Sulfur-Column-JT 337
                        :Feed-Nitrogen-Column-DA 338
                        :Product-Nitrogen-Column-JU 339
                        :Feed-Gravity-Column-CX 340
                        :Feed-Silicon-Column-DC 341
                        :Feed-Arsenic-Column-DD 342
                        :10-Per-Trendline-Column-EJ 343
                        :30-Per-Trendline-Column-EL 344
                        :50-Per-TrendlineColumn-EN 345
                        :70-Per-Trendline-Column-EP 346
                        :90-Per-Trendline-Column-ER 347
                        :100-Per-Trendline-Column-ET 348
                        :Feed-600ºF-Column-EW 349
                        :Feed-Rate-Column-C 350
                        :Feed-Ratio-Of-Cracked-Feed-Column-H 351
                        :Observed-WABT-Column-LJ 352
                        :Rate-Column-K 353
                        :Hydrogen-Purity-Column-L 354
                        :Rate-Column-M 355
                        :Hydrogen-Purity-Column-N 356
                        :Rate-Column-W 357
                        :Hydrogen-Purity-Column-P 358
                        :Rate-Column-AA 359
                        :Hydrogen-Purity-Column-AB 360
                        :Total-gas/oil-ratio-Column-LF 361
                        :Hydrogen/oil-ratio-Column-LG 362
                        :Train-A-Column-KU 363
                        :Train-B-Column-KV 364
                        :Hydrogen-Availability-Column-KZ 365
                        :Train-A-Inlet-Pressure-Column-AD 366
                        :Train-B-inlet-Pressure-Column-AH 367
                        :Train-A-Hydrogen-Partial-Pressure-Column-LA 368
                        :Train-B-Hydrogen-Partial-Pressure-Column-LB 369
                        :Total-Pressure-Drop-Column-AG 370
                        :Normalized-Pressure-Drop-Column-LC 371
                        :Total-Pressure-Drop-Column-AK 372
                        :Normalized-Pressure-Drop-Column-LD 373
                        :Train-A-DT-Column-AY 374
                        :Train-B-DT-Column-BM 375
                        :A1-Bed-1-DT-Column-AO 376
                        :A1-Bed-2-DT-Column-AS 377
                        :A2-DT-Column-AX 378
                        :B1-Bed-1-DT-Column-BC 379
                        :B1-Bed-2-DT-Column-BG 380
                        :B2-DT-Column-BL 381
                        :A1-Bed-1-inlet-T-Column-AL 382
                        :A1-Bed-1-outlet-T-Column-AN 383
                        :A1-Bed-2-outlet-T-Column-AR 384
                        :A2-outlet-T-Column-AW 385
                        :B1-Bed-1-inlet-T-Column-AZ 386
                        :B1-Bed-1-outlet-T-Column-BB 387
                        :B1-Bed-2-outlet-T-Column-BF 388
                        :B2-outlet-T-Column-BK 389
                        :Top-radial-spread-Column-BZ 390
                        :Bottom-radial-spread-Column-CA 391
                        :Top-radial-spread-Column-CB 392
                        :Middle-radial-spread-Column-CC 393
                        :Bottom-radial-spread-Column-CD 394
                        :Radial-spread-Column-CE 395
                        :Top-radial-spread-Column-CF 396
                        :Bottom-radial-spread-Column-CG 397
                        :Top-radial-spread-Column-CH 398
                        :Middle-radial-spread-Column-CI 399
                        :Bottom-radial-spread-Column-CJ 400
                        :Radial-spread-Column-CK 401
                        })


#_(def raw-sensor {
                 :Normalized-HDS-WABT-Column-MI 147
                 :Normalized-HDB-WABT-Column-MS 148
                 :Feed-Sulfur-Column-CZ  149
                 :Product-Sulfur-Column-JT  150
                 :Feed-Nitrogen-Column-DA  151
                 :Product-Nitrogen-Column-JU  152
                 :Feed-Gravity-Column-CX  153
                 :Feed-Silicon-Column-DC  154
                 :Feed-Arsenic-Column-DD  155
                 :10-Per-Trendline-Column-EJ  156
                 :30-Per-Trendline-Column-EL  157
                 :50-Per-TrendlineColumn-EN  158
                 :70-Per-Trendline-Column-EP  159
                 :90-Per-Trendline-Column-ER  160
                 :100-Per-Trendline-Column-ET  161
                 :Feed-600ºF-Column-EW  162
                 :Feed-Rate-Column-C  163
                 :Feed-Ratio-Of-Cracked-Feed-Column-H  164
                 :Observed-WABT-Column-LJ  165
                 :Rate-Column-K  166
                 :Hydrogen-Purity-Column-L  167
                 :Rate-Column-M  168
                 :Hydrogen-Purity-Column-N  169
                 :Rate-Column-W  170
                 :Hydrogen-Purity-Column-P  171
                 :Rate-Column-AA  172
                 :Hydrogen-Purity-Column-AB  173
                 :Total-gas/oil-ratio-Column-LF  174
                 :Hydrogen/oil-ratio-Column-LG  175
                 :Train-A-Column-KU  176
                 :Train-B-Column-KV  177
                 :Hydrogen-Availability-Column-KZ  178
                 :Train-A-Inlet-Pressure-Column-AD  179
                 :Train-B-inlet-Pressure-Column-AH  180
                 :Train-A-Hydrogen-Partial-Pressure-Column-LA  181
                 :Train-B-Hydrogen-Partial-Pressure-Column-LB  182
                 :Total-Pressure-Drop-Column-AG  183
                 :Normalized-Pressure-Drop-Column-LC  184
                 :Total-Pressure-Drop-Column-AK  185
                 :Normalized-Pressure-Drop-Column-LD  186
                 :Train-A-DT-Column-AY  187
                 :Train-B-DT-Column-BM  188
                 :A1-Bed-1-DT-Column-AO  189
                 :A1-Bed-2-DT-Column-AS  190
                 :A2-DT-Column-AX  191
                 :B1-Bed-1-DT-Column-BC  192
                 :B1-Bed-2-DT-Column-BG  193
                 :B2-DT-Column-BL  194
                 :A1-Bed-1-inlet-T-Column-AL 195
                 :A1-Bed-1-outlet-T-Column-AN  196
                 :A1-Bed-2-outlet-T-Column-AR  197
                 :A2-outlet-T-Column-AW  198
                 :B1-Bed-1-inlet-T-Column-AZ  199
                 :B1-Bed-1-outlet-T-Column-BB  200
                 :B1-Bed-2-outlet-T-Column-BF  201
                 :B2-outlet-T-Column-BK  202
                 :Top-radial-spread-Column-BZ  203
                 :Bottom-radial-spread-Column-CA  204
                 :Top-radial-spread-Column-CB  205
                 :Middle-radial-spread-Column-CC  206
                 :Bottom-radial-spread-Column-CD  207
                 :Radial-spread-Column-CE  208
                 :Top-radial-spread-Column-CF  209
                 :Bottom-radial-spread-Column-CG  210
                 :Top-radial-spread-Column-CH  211
                 :Middle-radial-spread-Column-CI  212
                 :Bottom-radial-spread-Column-CJ  213
                 :Radial-spread-Column-CK  214 })

#_(def raw-sensor {:Normalized-HDS-WABT-Column-MI-i  147
                   :Normalized-HDB-WABT-Column-MS-i 148
                   :Normalized-HDS-WABT-Column-MI :02THDSBT
                 :Normalized-HDB-WABT-Column-MS :02THDNBT
                 :Feed-Sulfur-Column-CZ :02WFSUL
                 :Product-Sulfur-Column-JT :02WPRSUL
                 :Feed-Nitrogen-Column-DA :02WFNIT
                 :Product-Nitrogen-Column-JU :02WPRNIT
                 :Feed-Gravity-Column-CX :02DFGRAV
                 :Feed-Silicon-Column-DC :02WFSIL
                 :Feed-Arsenic-Column-DD :02WFARS
                 :10-Per-Trendline-Column-EJ :02TFDIS10
                 :30-Per-Trendline-Column-EL :02TFDIS30
                 :50-Per-TrendlineColumn-EN :02TFDIS50
                 :70-Per-Trendline-Column-EP :02TFDIS70
                 :90-Per-Trendline-Column-ER :02TFDIS90
                 :100-Per-Trendline-Column-ET :02TFDIS100
                 :Feed-600ºF-Column-EW :02VF600F
                 :Feed-Rate-Column-C :02FFRATE
                 :Feed-Ratio-Of-Cracked-Feed-Column-H :02VFCRFEED
                 :Observed-WABT-Column-LJ :02TFOBBT
                 :Rate-Column-K :02FFMAKEUP
                 :Hydrogen-Purity-Column-L :02VPURH
                 :Rate-Column-M :02FRGAS
                 :Hydrogen-Purity-Column-N :02VPRGASH
                 :Rate-Column-W :02FQGAS
                 :Hydrogen-Purity-Column-P :02VPQGASH
                 :Rate-Column-AA :02FTGAS
                 :Hydrogen-Purity-Column-AB :02VPTGASH
                 :Total-gas/oil-ratio-Column-LF :02VGASOIL
                 :Hydrogen/oil-ratio-Column-LG :02VGASOILH
                 :Train-A-Column-KU :02VHTRNA
                 :Train-B-Column-KV :02VHTRNB
                 :Hydrogen-Availability-Column-KZ :02RHYDAV
                 :Train-A-Inlet-Pressure-Column-AD :02PTRNA
                 :Train-B-inlet-Pressure-Column-AH :02PTRNB
                 :Train-A-Hydrogen-Partial-Pressure-Column-LA :02PTRNAH
                 :Train-B-Hydrogen-Partial-Pressure-Column-LB :02PTRNBH
                 :Total-Pressure-Drop-Column-AG :02PTRNAPD
                 :Normalized-Pressure-Drop-Column-LC :02PTRNAPDN
                 :Total-Pressure-Drop-Column-AK :02PTRNBPD
                 :Normalized-Pressure-Drop-Column-LD :02PTRNBPDN
                 :Train-A-DT-Column-AY :02TTRNADT
                 :Train-B-DT-Column-BM :02TTRNBDT
                 :A1-Bed-1-DT-Column-AO :02TA1B1DT
                 :A1-Bed-2-DT-Column-AS :02TA1B2DT
                 :A2-DT-Column-AX :02TA2DT
                 :B1-Bed-1-DT-Column-BC :02TB1B1DT
                 :B1-Bed-2-DT-Column-BG :02TB1B2DT
                 :B2-DT-Column-BL :02TB2DT
                 :A1-Bed-1-inlet-T-Column-AL :02TA1B1IL
                 :A1-Bed-1-outlet-T-Column-AN :02TA1B1OL
                 :A1-Bed-2-outlet-T-Column-AR :02TA1B2OL
                 :A2-outlet-T-Column-AW :02TA2OL
                 :B1-Bed-1-inlet-T-Column-AZ :02TB1B1IL
                 :B1-Bed-1-outlet-T-Column-BB :02TB1B1OL
                 :B1-Bed-2-outlet-T-Column-BF :02TB1B2OL
                 :B2-outlet-T-Column-BK :02TB2OL
                 :Top-radial-spread-Column-BZ :02TAR1B1TR
                 :Bottom-radial-spread-Column-CA :02TAR1B1BR
                 :Top-radial-spread-Column-CB :02TAR1B2TR
                 :Middle-radial-spread-Column-CC :02TAR1B2MR
                 :Bottom-radial-spread-Column-CD :02TAR1B2BR
                 :Radial-spread-Column-CE :02TAR2R
                 :Top-radial-spread-Column-CF :02TBR1B1TR
                 :Bottom-radial-spread-Column-CG :02TBR1B1BR
                 :Top-radial-spread-Column-CH :02TBR1B2TR
                 :Middle-radial-spread-Column-CI :02TBR1B2MR
                 :Bottom-radial-spread-Column-CJ :02TBR1B2BR
                 :Radial-spread-Column-CK :02TBR2R})

(def calculated-data-uom {:Normalized-HDS-WABT-Column-MI  "deg.F"
                           :Normalized-HDB-WABT-Column-MS  "deg.F"
                           :Feed-Sulfur-Column-CZ  "wt%"
                           :Product-Sulfur-Column-JT  "wtppm"
                           :Feed-Nitrogen-Column-DA  "wt%"
                           :Product-Nitrogen-Column-JU  "wt%"
                           :Feed-Gravity-Column-CX  "SG"
                           :Feed-Silicon-Column-DC  "wtppm"
                           :Feed-Arsenic-Column-DD  "wtppm"
                           :10-Per-Trendline-Column-EJ  "deg.F"
                           :30-Per-Trendline-Column-EL  "deg.F"
                           :50-Per-TrendlineColumn-EN  "deg.F"
                           :70-Per-Trendline-Column-EP  "deg.F"
                           :90-Per-Trendline-Column-ER  "deg.F"
                           :100-Per-Trendline-Column-ET  "deg.F"
                           :Feed-600ºF-Column-EW  "vol%"
                           :Feed-Rate-Column-C  "BPD"
                           :Feed-Ratio-Of-Cracked-Feed-Column-H  "vol%"
                           :Observed-WABT-Column-LJ  "deg.F"
                           :Rate-Column-K  "SCFH"
                           :Hydrogen-Purity-Column-L  "vol%"
                           :Rate-Column-M  "SCFH"
                           :Hydrogen-Purity-Column-N  "vol%"
                           :Rate-Column-W  "SCFH"
                           :Hydrogen-Purity-Column-P  "vol%"
                           :Rate-Column-AA  "MMSCFD"
                           :Hydrogen-Purity-Column-AB  "vol%"
                           :Total-gas/oil-ratio-Column-LF  "SCF/bbl"
                           :Hydrogen/oil-ratio-Column-LG  "SCF/bbl"
                           :Train-A-Column-KU  "SCF/bbl"
                           :Train-B-Column-KV  "SCF/bbl"
                           :Hydrogen-Availability-Column-KZ  nil
                           :Train-A-Inlet-Pressure-Column-AD  "psig"
                           :Train-B-inlet-Pressure-Column-AH  "psig"
                           :Train-A-Hydrogen-Partial-Pressure-Column-LA  "psia"
                           :Train-B-Hydrogen-Partial-Pressure-Column-LB  "psia"
                           :Total-Pressure-Drop-Column-AG  "psi"
                           :Normalized-Pressure-Drop-Column-LC  "psi"
                           :Total-Pressure-Drop-Column-AK  "psi"
                           :Normalized-Pressure-Drop-Column-LD  "psi"
                           :Train-A-DT-Column-AY  "deg.F"
                           :Train-B-DT-Column-BM  "deg.F"
                           :A1-Bed-1-DT-Column-AO  "deg.F"
                           :A1-Bed-2-DT-Column-AS  "deg.F"
                           :A2-DT-Column-AX  "deg.F"
                           :B1-Bed-1-DT-Column-BC  "deg.F"
                           :B1-Bed-2-DT-Column-BG  "deg.F"
                           :B2-DT-Column-BL  "deg.F"
                           :A1-Bed-1-inlet-T-Column-AL  "deg.F"
                           :A1-Bed-1-outlet-T-Column-AN  "deg.F"
                           :A1-Bed-2-outlet-T-Column-AR  "deg.F"
                           :A2-outlet-T-Column-AW  "deg.F"
                           :B1-Bed-1-inlet-T-Column-AZ  "deg.F"
                           :B1-Bed-1-outlet-T-Column-BB  "deg.F"
                           :B1-Bed-2-outlet-T-Column-BF  "deg.F"
                           :B2-outlet-T-Column-BK  "deg.F"
                           :Top-radial-spread-Column-BZ  "deg.F"
                           :Bottom-radial-spread-Column-CA  "deg.F"
                           :Top-radial-spread-Column-CB  "deg.F"
                           :Middle-radial-spread-Column-CC  "deg.F"
                           :Bottom-radial-spread-Column-CD  "deg.F"
                           :Radial-spread-Column-CE  "deg.F"
                           :Top-radial-spread-Column-CF  "deg.F"
                           :Bottom-radial-spread-Column-CG  "deg.F"
                           :Top-radial-spread-Column-CH  "deg.F"
                           :Middle-radial-spread-Column-CI  "deg.F"
                           :Bottom-radial-spread-Column-CJ  "deg.F"
                           :Radial-spread-Column-CK  "deg.F"

                           })
